# syntax=docker/dockerfile:1

ARG RUBY_VERSION=3.4.8
FROM docker.io/library/ruby:$RUBY_VERSION-slim

WORKDIR /rails

# Instala dependências necessárias para dev
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      build-essential \
      git \
      libpq-dev \
      libyaml-dev \
      pkg-config \
      curl \
      postgresql-client \
      libvips \
    && rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Ambiente de desenvolvimento
ENV RAILS_ENV=development \
    BUNDLE_PATH=/usr/local/bundle \
    BUNDLE_WITHOUT="" \
    BUNDLE_FROZEN=false

# Copia apenas Gemfiles primeiro (melhora cache)
COPY Gemfile Gemfile.lock ./

RUN bundle install

# Depois copia o restante da aplicação
COPY . .

RUN chmod +x /rails/bin/docker-entrypoint \
 && chmod +x /rails/bin/*

ENTRYPOINT ["/rails/bin/docker-entrypoint"]

EXPOSE 3000

CMD ["bin/rails", "server", "-b", "0.0.0.0", "-p", "3000"]